### ISSUE TITLE
Consider to our work into your great repo

### ISSUE THREAD

**Issue by YangLing0818** [xinchengshuai/Awesome-Image-Editing#1]
Hi! This is a great repo to record the image editing.

Would you like to add our latest instruction-based image editing method into your repo and survey.

EditWorld: Simulating World Dynamics for Instruction-Following Image Editing. 2024.

Arxiv: https://arxiv.org/abs/2405.14785

Code: https://github.com/YangLing0818/EditWorld

**Comment by xinchengshuai** [comment]
Thanks for your attention to our work. We have updated the repo and will add your work in the next version of the survey.
